# fly.toml app configuration file generated for sprintpadawan on 2023-11-17T00:05:08-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sprintpadawan"
primary_region = "sea"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]
